### ISSUE TITLE
fatal error: lv2/lv2plug.in/ns/lv2core/lv2.h: No such file or directory

### ISSUE THREAD

**Issue by ghost** [quamplex/geonkick#1]
I am trying to compile geonkick on ubuntu 23.04 and encounter an error at compilation (all dependencies have been installed).

```
[ 99%] Building CXX object src/plugin/lv2/CMakeFiles/geonkick_lv2.dir/geonkick_lv2.cpp.o
/home/$USER/Desktop/geonkick/src/plugin/lv2/geonkick_lv2.cpp:24:10: fatal error: lv2/lv2plug.in/ns/lv2core/lv2.h: No such file or directory
   24 | #include <lv2/lv2plug.in/ns/lv2core/lv2.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/plugin/lv2/CMakeFiles/geonkick_lv2.dir/build.make:76: src/plugin/lv2/CMakeFiles/geonkick_lv2.dir/geonkick_lv2.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:471: src/plugin/lv2/CMakeFiles/geonkick_lv2.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

I did some research and it might be because the newer versions of lv2 break backwards compatibility

Sources:

* https://discourse.ardour.org/t/problem-compiling-7-4/108697/2
* https://github.com/lv2/lv2#user-content-headers
* https://github.com/KXStudio/Repository/issues/303

**Comment by iurienistor** [comment]
@reahari Hi, I'll check. Probably LV2 released a new version, so, they had to break backward compatibility.

**Comment by iurienistor** [comment]
For now I'll not modify to use the new headers, but in the future maybe. For now I'll close this issue because this due to some distros turning off old LV2 headers... if I am not wrong.

**Comment by hellocatfood** [comment]
I just tried to compile this now and had the same issue. Could this be reopened until there's a fix?
