### ISSUE TITLE
Geonkick UI and System Lag

### ISSUE THREAD

**Issue by RobU23** [quamplex/geonkick#10]
Hi, 

Thanks for bringing such a cool tool to Windows !  Unfortunately, there are some teething issues on my system (i4790, 32GB).

Getting serious lagging in the GUI with the VST3 version on Windows 10, Reaper 7 and Bitwig 5.1, which is also causing my entire system to become highly unresponsive.

At first, Geonkick works as expected, but after some time editing (no more than 5 mins), the GUI starts to lag, buttons go missing, switching between Control / Kit / Presets becomes so slow that you can see the widgets drawing one by one.  By this time, overall system lag is huge, system windows start lagging and other applications become unresponsive.  Unusually, I don't see any processes running higher than expected in Task Manager, even though TM itself is extremely laggy.  It gets so slow that I can manually activate my screenshot software before the UI has refreshed when switching back to the Controls tab (see below).

The issue can be temporarily resolved by closing the plugin UI then reopening it - this seems to reset the plugin graphics stack, at least for another 5 minutes of editing.

![Geonkick_2023-12-10 163641](https://github.com/Geonkick-Synthesizer/geonkick/assets/24913764/f695cf1d-4c0f-4e58-9e98-fa9fae47ab10)

Cheers
RobU

**Comment by iurienistor** [comment]
Hi, thanks for reporting this. The core GUI of the plugin was recently ported to Windows and there is a need for improvements and fixing. This will be a priority.

**Comment by iurienistor** [comment]
@RobU23  I can confirm this behavior, it can be reproduced if switching the tabs for some time (10-15 times)... This is not related to graphics, the event queue of Geonkick GUI for Windows probably is not cleared properly. I'll work on this.

**Comment by RobU23** [comment]
Many thanks for looking into this, @iurienistor.

**Comment by iurienistor** [comment]
@RobU23 I think I already fixed this... soon, i'll create a commit.

**Comment by iurienistor** [comment]
@RobU23 Here is the commit - https://github.com/Geonkick-Synthesizer/geonkick/commit/82f0618f06a0e411fa5237bc747dea90a8a55d62 soon the pipeline will build the installer, and you can try if you have the same problems - https://github.com/Geonkick-Synthesizer/geonkick/actions

**Comment by RobU23** [comment]
Hi Iurie,

Took me a while to find the new installer ... However, that has definitely
fixed the issue with the lagging in both the multi VST3 and the single LV2
(which I didn't know about but it installed anyway and it runs well in
Reaper), nice one!

A couple of other things I noticed in both versions, the Compression and
Distortion cannot be activated.  Not a big deal at the moment, and you
probably know but I thought I would mention it anyway : )

Anyway, it's behaving much better now, many thanks for the quick turnaround.

Rob.U

**Comment by iurienistor** [comment]
@RobU23 Sorry, the build artifacts on gitgub are hard to find and confusing. The fix will be released soon in the next release, so, the installer could be found on the Geonkick website or in the release notes.

The distortion and  "compressor" (this is not a really compressor, better to call it distortion Nr 2 :) ), they are active, but it is a bug I need to fix in the next bugfix release.

LV2 version of the plugin you should see in the daw as single and as kit instrument, for vst for now is only as kit, the single needs some more coding and is not yet available.
