### ISSUE TITLE
[FR] - Allow Browsing other drives than C:\ (Windows VST3 only)

### ISSUE THREAD

**Issue by RobU23** [quamplex/geonkick#11]
Hi, 

I may be missing something, but I cannot change drives letters - the default path is always c:\

All of my samples are on another drive (d:) so I can't import them without first having to move them to the C drive.

It would be super useful to browse other drives (just a windows issue, I guess...).

Cheers
Rob.U

**Comment by iurienistor** [comment]
Yes, this needs to be implemented. I hope until next release.
