### ISSUE TITLE
GUI scale support for high density displays

### ISSUE THREAD

**Issue by hellocatfood** [quamplex/geonkick#14]
I'm using Geonkick on a computer with a 3840x2400 display and opening up the lv2 plugin of the gui has a very small interface with no way to resize it in both ardour and carla. Below a screenshot of the plugin against a full-sized carla window

![Screenshot from 2023-12-12 17-39-22](https://github.com/Geonkick-Synthesizer/geonkick/assets/151947/9bf0f308-edc9-4ab6-8993-af17aa64ca2c)

could support be added for high density displays?

**Comment by iurienistor** [comment]
@hellocatfood  For now this feature is available only on GNU/Linux, porting it to Windows happens on this branch, I hope soon will be ready - https://github.com/Geonkick-Synthesizer/geonkick/tree/feat/win_scalling

**Comment by hellocatfood** [comment]
Great to hear. I'm using linux. Is there a way to use this feature already?

**Comment by iurienistor** [comment]
@hellocatfood Ctrl+f increase/decrease the scale. Better than to close and open the plugin windows. I'll add a widgets dedicated to this setting... because shortcuts are problematic on some hosts.

**Comment by lgmacri** [comment]
Hi! I'm looking forward to using this feature in Windows, is that already implemented? Thanks!
