### ISSUE TITLE
(again)Windows version NOT work in some DAWs

### ISSUE THREAD

**Issue by lehsa4017** [quamplex/geonkick#15]
https://github.com/Geonkick-Synthesizer/geonkick/issues/4
Again this happen for me on version 3.1 just Ardour can find VST3 version Cakewalk and Ableton cant find it

**Comment by nowgad** [comment]
confirm: "The entry point to the inflateValidate procedure was not found in the DLL C:\Program Files\Geonkick\libpng16-16.dll"
Win10 Waveform 12.5.11

**Comment by iurienistor** [comment]
@nowgad  I think it is due to a conflict of a DLL version mismatch with another plugin or with the host. I am working on a build  setup to link statically these dependencies.

**Comment by iurienistor** [comment]
@lehsa4017 @lbnv

Now, I have linked all the dependencies statically, and no DLLs will be installed. You can try the installer at https://github.com/Geonkick-Synthesizer/geonkick/actions/runs/7258822972/artifacts/1123369589 (you may need to log in to GitHub to download). Please note that it has not been officially released yet.

Before installing the new version, make sure to uninstall the old version and ensure everything is clean. If there is still something remaining after uninstallation, follow these steps manually:

    Remove the path related to Geonkick from the PATH environment variables (very important).
    Remove the folder C:\Program Files\Geonkick (important).
    Remove everything from ProgramData and %APPDATA% (optional if anything remains).

Now, proceed to install the new plugin. After installation, there should be no folder named C:\Program Files\Geonkick, and there should be no references to Geonkick in the PATH environment variable.

By following these steps, I believe the problems should be resolved.

**Comment by iurienistor** [comment]
I think I'll close this issue as fixed. If for someone still is reproducible, please, reopen.

**Comment by lehsa4017** [comment]
Hi 
uninstall the old version > OK
Remove the path related to Geonkick from the PATH environment variables (very important). > OK
Remove the folder C:\Program Files\Geonkick (important). > OK
Remove everything from ProgramData and %APPDATA% (optional if anything remains). > OK
After installation, there should be no folder named C:\Program Files\Geonkick, > OK
no references to Geonkick in the PATH environment variable. > OK
But not work again

note to vstscanlog in end of this comment 
![image](https://github.com/Geonkick-Synthesizer/geonkick/assets/119779161/00c2becf-8b90-4b50-8f06-3ca12fa1e2df)
![image](https://github.com/Geonkick-Synthesizer/geonkick/assets/119779161/554a4075-3fd1-43c0-b073-22a9a94be6c4)
![image](https://github.com/Geonkick-Synthesizer/geonkick/assets/119779161/0eae08b8-0e0a-4b6a-8c24-aae10e78be05)
![image](https://github.com/Geonkick-Synthesizer/geonkick/assets/119779161/a2cb41c6-684b-4201-aaf8-d895aa1f7212)

note that screenshots of before install and after it are same
[VstScanSandbox.log](https://github.com/Geonkick-Synthesizer/geonkick/files/13737082/VstScanSandbox.log)
[VstScan.log](https://github.com/Geonkick-Synthesizer/geonkick/files/13737083/VstScan.log)

**Comment by lehsa4017** [comment]
work in Ableton but only vst3 version
![image](https://github.com/Geonkick-Synthesizer/geonkick/assets/119779161/f6009a0a-fa4e-4ffe-a9b2-c6bf97b1819e)
![image](https://github.com/Geonkick-Synthesizer/geonkick/assets/119779161/5e2588d1-7780-4cf8-986f-d7dd85bb467b)

**Comment by LuxiayKuragon** [comment]
Hi! I've installed the plugin and to me currently works in FLStudio but when I try to use it on Studio One 5 it makes very short bleep sounds and SO pops an error window that tells me that the plugin isn't working as expected and that i have to save and restart SO. I'm on W11.
