### ISSUE TITLE
Feature request: Allow MIDI note on to act as trigger (ignore note-off)

### ISSUE THREAD

**Issue by defensem3ch** [quamplex/geonkick#16]
It would be great if MIDI note on could optionally act as a trigger for the envelope; for example, crash cymbals would not be cut short when the note ends.

**Comment by iurienistor** [comment]
Hi, I'll think how to add this.

**Comment by iurienistor** [comment]
Implemented here, on main branch, will be available in the next release (3.3.0) : https://github.com/Geonkick-Synthesizer/geonkick/commit/66d4128a35a7f47a569052bc2dfe372f48037827
