### ISSUE TITLE
no Macos

### ISSUE THREAD

**Issue by ykrem** [quamplex/geonkick#17]
pretty self explanatory isn't it... would love to try this one!

**Comment by iurienistor** [comment]
@yonatankremer The core GUI of the plugin doesn't support this platform, there is a need for porting / implemention which is not trivial. Now there are other priorities tasks for core GUI aiming to address some fundamental issues , and after this maybe it will be ready for this kind of porting.

**Comment by windowsrefund** [comment]
This is a good thing. People who want to experience the benefits of free software should be running freedom-respecting operating systems. OP should run GNU/Linux.

**Comment by ykrem** [comment]
but... it's on windows? Have been considering linux but I'm not sure how beneficial It'll be for me

**Comment by windowsrefund** [comment]
Well, maybe you should figure that out for yourself?
