### ISSUE TITLE
request: fast switch between sounds in a kit for more convenience

### ISSUE THREAD

**Issue by MaZe6K** [quamplex/geonkick#18]
Hi there!

1st of all: This thing is really amazing, possibly the best drum synth to date!

Right now I just wish I could switch between the sounds in a kit a bit more rapidly when editing a kit.
Ideally I would like to hover the mouse over the name of the curent sound and switch through the kit with the mouse wheel, and/or open up a list of all sounds currently in the kit when clicking the name of the sound.

Just a small optional thing, but would make editing kits much more convenient, since currently it takes 3 clicks and moves to switch over to a different sound in the kit, which can get a bit annoying when switching back and forth a lot for making a kit.

**Comment by iurienistor** [comment]
@MaZe6K, if you mean that you want to switch the instrument, then yes, I think scrolling on the name to switch the current editing instrument is a good and easy-to-implement idea. I believe I'll implement it even in the next release. On the other hand, there are plans also to add the instrument names like tabs in the left-bottom of the window, but this requires more work to change the UI. Therefore, this one will be a little later.

**Comment by iurienistor** [comment]
Implemented here : https://github.com/Geonkick-Synthesizer/geonkick/issues/53
