### ISSUE TITLE
Open and Save dialogs

### ISSUE THREAD

**Issue by windowsrefund** [quamplex/geonkick#21]
Hello. I've just compiled 3.2.0 and am running the lv2 on GNU/Linux. Things seem fine and I thought the Open and Save dialogs were not functioning until I realized I could click on [ .local.. ] in order to (eventually) navigate my filesystem. The Home, Desktop, and Downloads choices on the left lead to nothing as well. All in all, it feels more like a quick mock of a dialog box? Are there plans to maybe lean into something that already exists on the system?

All the best

**Comment by windowsrefund** [comment]
Figured it might be worth mentioning I run on i3.Here's what things look like using the Open dialog

![open](https://github.com/Geonkick-Synthesizer/geonkick/assets/512222/4fb70377-2e23-48f6-adf8-53fac213dcc9)

Things get even worse when the ... button is used in either of the Oscillator areas. Notice how there's no way to close the dialog.

![trapped](https://github.com/Geonkick-Synthesizer/geonkick/assets/512222/51b92623-d533-4ef0-a196-56a019aa6277)

**Comment by iurienistor** [comment]
@windowsrefund Both screenshots are ok. In  the first one it is like a dialog. The second one is embedded the part of the "samples" tab (see the top bar), no close button is needed. 
 Regarding, Home, Desktops, etc... I'll check, probably on your distrio, they are different, and were not able to be taken from standard env variables. 

The plugins UI should not create any sistem dialogs of any kind... ideally it should use it's own graphics widgets, thus, browser must not be the system one... these creates problems for many hosts. Geonkick still creates window system widgets but gradually will move to it's own graphics one. Yes, the file browser needs improvements in look and functionality, but this wiill be done in the context of graphics widgets, no system one.

**Comment by windowsrefund** [comment]
Ah, I get it...  Clicking ... switched context to the Samples area. Got it.
