### ISSUE TITLE
segfault on export

### ISSUE THREAD

**Issue by KottV** [quamplex/geonkick#22]
Hi,

system: openSUSE TW gcc 8.3.1 glibc 2.29

geonkick crashes on export button press, both standalone and plugin
backtrace:

> Thread 1 "geonkick" received signal SIGSEGV, Segmentation fault.
> 0x0000000000687df0 in ?? ()
> (gdb) bt
> #0  0x0000000000687df0 in ?? ()
> #1  0x0000000000488224 in RkLineEdit::RkLineEditImpl::paintEvent(std::shared_ptr<RkPaintEvent> const&) ()
> #2  0x0000000000482841 in RkWidget::RkWidgetImpl::processEvent(std::shared_ptr<RkEvent> const&) ()
> #3  0x0000000000484270 in RkEventQueue::RkEventQueueImpl::processEvents() ()
> #4  0x0000000000485895 in RkMain::RkMainImpl::exec(bool) ()
> #5  0x0000000000412f1e in main ()
> (gdb)

**Comment by iurienistor** [comment]
Hi! Thank you for reporting this. I'll see what is happening. For now I can't reproduce on Debian, I'll check for openSUSE TW and other distros, hope to catch it.

**Comment by trebmuh** [comment]
Can't reproduce (Debian 9 here too), the export button works as expected.

**Comment by iurienistor** [comment]
Hi, Konstantin! I have fixed the problem. Thank you for reporting it, very important. What you need to do now is:
* update Redkite code from the master to be the version 0.5.2
* clean the build with (rm -fr ./* into build dir) and than cmake, make, and install Redkite
* clean the build for Geonkick (rm -fr ./* into build dir), cmake, make and install.

After this you should not experience the problem. Please, write back your result.
I have tried openSUSE for the first time now on my virtual, I like it.

**Comment by KottV** [comment]
Hi,
yes, problem is gone.

Thank You Iurie!
