### ISSUE TITLE
Feature request: optional paths during setup

### ISSUE THREAD

**Issue by parduz** [quamplex/geonkick#22]
I've just installed Geonkick and it asked nothing, just installed the VST3 in the usual folder and the presets inside the user path.

I have a dedicated disk for all my music stuffs (S:\) and **everything** is installed there. I also have 2 OSs on my PC, one "for everyday use" and one super clean and optimized for music production. I have my DAW in both OSs, and both are configure to look in S: for the plugins, the presets etc.

I reckon that my use case is not the most common, but also it is not something really weird.

Some plugins won't allow this, so i use symlinks in the various "appdata" folders to make those VST happy while still having all the data in the S: disk.
I wonder if geonkick could be smarter than that and allow to have a custom setup picking paths both for the plugins and for the presets.

**Comment by iurienistor** [comment]
Yes, in the next releases the installer  for Windows will gradually improve, adding staff like path selection, plugin format and other features.
