### ISSUE TITLE
Improve filters

### ISSUE THREAD

**Issue by tavasti** [quamplex/geonkick#23]
With play active, if I turn any filter knob to max, plugin will start producing audio signal with high volume, so that real signal is clipped away. And with low pass filter, there should not be any problem turning filter freq up, because that will just mean 'no filter'.

See https://youtu.be/8u9I0FL9jdA

**Comment by tavasti** [comment]
With mixbus sound will be permanently silenced, needs closing project & reopening to recover :-(

**Comment by iurienistor** [comment]
Filter becomes unstable for some extrimal parameters. You need to use also resonace to make cuttof to work in the range. i  limited the output when becomes unstable , so there will not be sound, and you"l get a max contious line in the graph, but probably that limit is too high and daw blocks comletely the output even you turn back the filters in the workable ranges. ill think how ill make, so users not to experience this.... thank you! ill turn this into an issue for next releases.
