### ISSUE TITLE
Export button vanished?

### ISSUE THREAD

**Issue by DerozerDSP** [quamplex/geonkick#23]
Hi,

got the 3.2.0 version right now, but it seems there isn't the Export button?

<img width="479" alt="image" src="https://github.com/Geonkick-Synthesizer/geonkick/assets/19835752/a6a3c2a8-ae65-40f5-8c53-d1bd592b3fbe">

How can I enable it? It seems there is on the official screenshot on your website: 

<img width="687" alt="image" src="https://github.com/Geonkick-Synthesizer/geonkick/assets/19835752/be89407f-0cce-4cf9-a388-4fe7498f2105">

Thanks for any tips.

**Comment by iurienistor** [comment]
@DerozerDSP Hi, Export button on Windows is not yet available because the dialog contains some specific things that needs implementation on Windows. But you can export from the "Kit" tab, as sfz format which also will creates a folder with wave format of the sound.

**Comment by DerozerDSP** [comment]
@iurienistor I see, thanks for the fast reply.

Well, meanwhile I recorded "live" a basic kick/sine using an Editor, but it seems that having 1 single layer, sine wave, amplitude all up (i.e. x1.0 I believe), doesn't match what is showed in the graph and what it actually play:

<img width="1000" alt="image" src="https://github.com/Geonkick-Synthesizer/geonkick/assets/130961671/0461fbfe-6a95-4392-9652-5b8ec40de5ed">

If you see on the right, the peak are higher than 1.0, it seems there is something more that increase the whole level of the output signal?

Am I missing some further knob/level multipler?

**Comment by DerozerDSP** [comment]
Ok, I think I got the "problem" of my previous post: its the main level on the right panel. 
If I set it to 0, it seems it plays at -3db:

<img width="1000" alt="image" src="https://github.com/Geonkick-Synthesizer/geonkick/assets/130961671/1d0a8826-9aa7-4355-b37a-8fa5a0dd2b55">

Is it that normal? How can I play it full scale at 0db/1.0 peak? Did you scale internally -3db? Not sure how to set a precise value (i.e. -3.01db).

**Comment by iurienistor** [comment]
@DerozerDSP "Is it that normal? How can I play it full scale at 0db/1.0 peak? Did you scale internally -3db? "... No, but I'll check this behavior.

**Comment by DerozerDSP** [comment]
@iurienistor perfect! I'll wait some feed from you so, thanks.

**Comment by DerozerDSP** [comment]
Hi @iurienistor : news about this point? Are you able to reproduce it? Otherwise I'll give you the patch....

**Comment by iurienistor** [comment]
export audio button is back, to be released in v3.5
