### ISSUE TITLE
Feature request: reset knobs/sliders

### ISSUE THREAD

**Issue by DerozerDSP** [quamplex/geonkick#24]
Hi,

I think its not possible to reset knobs/sliders right now.
Tried Double click, ctrl+click, shift-click: nothing works.

Can you add such a feature? I think its a must-have on any plugin/vst (I'm on Windows).
Note: I'm on FL Studio, and on Browse Parameters I can't even see the linked params on DAW, where usually I click "reset" from there.

Thanks

**Comment by iurienistor** [comment]
@DerozerDSP Geonkick currently does not expose any parameters. However, the introduction of control reset functionality is planned.
