### ISSUE TITLE
Export location's feature request

### ISSUE THREAD

**Issue by trebmuh** [quamplex/geonkick#25]
(_geonkick 1.5 here_)

Case scenario :
- go to the exporting dialog
- choose a folder where to export the audio
- export the audio
- come back to the main geonkick window
- change some stuff
- re-go to the exporting dialog

-> the location is back to the defaulting one

Suggestion: make it possible for the previously chosen location to be remembered.

**Comment by iurienistor** [comment]
Yes, I a gree. I'll implement it. Thank you for suggesting it! I'll try develop this for 1.6 minor, if not it will be passed to next minor releases.

**Comment by iurienistor** [comment]
Implemented. The first time when opening the main window the current working path will be default. The new working path is set every time new path is selected,  and is lost when the main window is closed for standalone. The same is for save / open preset. For LV2 current path is lost only if DAW is closed or the plugin is removed, on closing and open GUI for LV2 the path is preserved. In the next releases I'll implemented this to be completely persistent, but there is a need to do this to be cross-platform. Thank you for your suggestion!
