### ISSUE TITLE
Geonkick crashes on Windows 11

### ISSUE THREAD

**Issue by bird0912** [quamplex/geonkick#25]
Geonkick on Reaper 7 and Ardour 7 doesn't load, causing a sudden crash where the software, in fact it doesn't even freezes, it just closes. I thought that maybe it was a sampling rate related crash but it is not since i tried it on multiple audio settings and DAWs. I'm currently running: 
Windows 11 Pro 22H2
AMD Ryzen 5 4600H with Radeon Graphics            3.00 GHz
16.0 GB 

Any help would be amazing since I've been waiting to try the windows version from like 5 years ago when i saw Unfa using it on Arch :3 good times :D

**Comment by iurienistor** [comment]
@bird0912 Hi, I have never checked the plugin under Win11 only under Win10, maybe it is not compatible, but I'll check.

**Comment by bird0912** [comment]
Ohhh I didn't though about a OS problem, good point! Thank for the answer! I'll keep an eye out ;3
