### ISSUE TITLE
The installer is a little bit frustrative and feedback / first impressions about the UX 

### ISSUE THREAD

**Issue by o-bardiuk** [quamplex/geonkick#26]
I ran it and it silently installed the plugin. Then I tried to re-run it and it just closed itself. I thought it was crashing. A pop-up with a notification about successful installation would be nice to have.

Thanks for the great work, I really like the UI, it's very fast and kind of intuitive. But I would like to share my experience. I have a lot of experience with various VST plugins.

1) I am on Windows and I didn't get where the presets are installed if there are any. 
UPD: Ok, I have scanned my system and found them in `c:\ProgramData\geonkick\presets\` though I was expecting them in User/name/Documents like other plugins do on Windows;

2) Also kits... I really like the feature. I thought it'll be some Kick2 rip off but it has much more. I like the idea of the fully synthesized drum kit in a plugin. But why did you make different channels per sound? Like... who will ever guess that every sound is a separate channel?
When I load a plugin I expect that when I hit C1 or C3 I will hear some sound. In the `Kit Avl Drum kit` preset, you mapped sounds starting with A4 and different channels.
I think most users will feel like it doesn't work. IMO it should be something like this
![image](https://github.com/Geonkick-Synthesizer/geonkick/assets/139021881/1c5ba605-887b-47fd-abb2-546fa82ea22e)

3) Maybe there should be a close button. Because you can only close it when you click somewhere on the main window but before I knew it I thought that the window hung. Also your C2 is C1/36 in Cubase, IDK why.
![image](https://github.com/Geonkick-Synthesizer/geonkick/assets/139021881/5c99d04b-33d9-42b2-a068-babaf5728ae4)

I have figured out that when you click on the plugin itself - the window will get closed. But if you click anywhere on the DAW the window will be still open and it's kind of bad, I guess.

4) Prevent of creation of a new dot at the same place on double click. Most famous synths like Serum will create or erase the dot if you double-click twice at the same place. In Genokick it will create yet another dot at the same place. And left button could be used for the context menu with some functions.
![image](https://github.com/Geonkick-Synthesizer/geonkick/assets/139021881/d97cce6f-4796-4131-9bf7-19fa15e63f98)

5) I have no idea what these icons mean.
![image](https://github.com/Geonkick-Synthesizer/geonkick/assets/139021881/202c7933-1cd2-4bf1-b73f-36e6a00dcdec)

6) the scroll doesn't work correctly, when I try to click it or mouse wheel over it - the window becomes closed
![image](https://github.com/Geonkick-Synthesizer/geonkick/assets/139021881/0bf6eb16-ac06-4807-b6ba-bdee69d9ec38)

7) All presets must be reworked on C1-C3 because it takes too much burden just to listen to a preset on a two-octave MIDI keyboard. I need to retune every sound to C1 to be able to hear it. But I kind of like the idea that if the kit is created (many instances of samplers) you then reload a preset and it goes into the kit's slot. That's kind of cool. I dig it. But maybe new/inexperienced users will not get it.

~UPD: I know! There can be a checkbox, if you click it then every key on a keyboard triggers the audio output.~
I got it, there actually is the `any` key, awesome!!

I got the idea, if you load a kit, you load a bunch of instances into the list, if you load a preset - you load a single instance.
Maybe a different browser for different types of presents (i.e. single vs a kit) would be better for this. Or there should be a confirmation window that you might destroy the current kit and load the other one.

I am writing this because I thought it might be helpful to read feedback about your plugin from a man that seen it for the first time.

Oh, and the last one - please 🙏 make a zoom of this area, it is very needed for precise kicks.
![image](https://github.com/Geonkick-Synthesizer/geonkick/assets/139021881/843e1f0c-8691-4bae-bddb-b63cdac8e513)

And this idea:
![image](https://github.com/Geonkick-Synthesizer/geonkick/assets/139021881/c4930925-34ef-41e3-bcb7-522ddd45b89c)

Good luck and keep up the great work!

UPD3: for 40 minutes of using the plugin I didn't get that these are buttons and you can click them to see the envelope, wow cool! Awesome! 😱 I thought they were just highlighted labels :)
![image](https://github.com/Geonkick-Synthesizer/geonkick/assets/139021881/a85fe455-0b37-44bc-9383-8d14eac0ef85)

UPD4: and I finally got this, it's not midi channels, it's audio channels! I see, cool! I was wondering why sounds don't work, it was because of different audio channels, not MIDI, got it! 👌
 
![image](https://github.com/Geonkick-Synthesizer/geonkick/assets/139021881/47daaa44-9c56-4c09-8b31-6e632ea27a7a)

**Comment by iurienistor** [comment]
@o-bardiuk Hi, thanks for the valuable feedback. I'll return with a more careful analysis, and what can be implemented.

**Comment by iurienistor** [comment]
Installer was updated now (it supports also custom paths), it will be released, see the changelog file.

1. c:\ProgramData\geonkick\presets\ will remain the same, I don't think user/Documents is the right place for factory presets of a plugin.

1 . For zoom was I created a issue here: https://github.com/Geonkick-Synthesizer/geonkick/issues/26
2. "When I load a plugin I expect that when I hit C1 or C3 I will hear some sound. In the Kit Avl Drum kit preset, you mapped sounds starting with A4 and different channels."... I'll check if this should be changed not, created an issue: https://github.com/Geonkick-Synthesizer/geonkick/issues/30
3. Create issue https://github.com/Geonkick-Synthesizer/geonkick/issues/31
4. Created issue: https://github.com/Geonkick-Synthesizer/geonkick/issues/32
5. See the documentation: https://github.com/Geonkick-Synthesizer/geonkick/blob/main/doc/Geonkick_User_Guide.md
6. I'll check - https://github.com/Geonkick-Synthesizer/geonkick/issues/33
7. is the same as 2
8. "Maybe a different browser for different types of presents (i.e. single vs a kit) would be better for this. Or there should be a confirmation window that you might destroy the current kit and load the other one"... the file browser is different for instrument and kit preset... see the documentation
9. Can be moved the + button, but this UI in general will reworked be a little and probably things will be changed.

Thanks, for the feedback, I created the issues for what to clarify or implement, but this current one I'll close. If you have any other issue, or ideas, please, create an issue.
