### ISSUE TITLE
Add FM synthesis

### ISSUE THREAD

**Issue by iurienistor** [quamplex/geonkick#28]
Add FM synthesis. At least to permit algoritms of combination of 3 operators per layer.

**Comment by SpotlightKid** [comment]
Even simple 2-op FM between Osc 1+2 would be already very useful.

**Comment by iurienistor** [comment]
@SpotlightKid Ah, thank you. Than it means I am on a right path. :)

**Comment by iurienistor** [comment]
I have implemented FM synthesis (branch  feat/fm) for OSC1->OSC2. When enabling the label OSC1->OSC2, OSC2 will be FM modulated by OSC1. This can be set separately for layer. I am still not sure about the coefficient of the modulation... for now is 100%... i.e. for maximum amplitude of the OSC1 corresponds to modulation from 0 to max frequency set for OSC2. Very interesting result when modifying the amplitude envelope of the OSC1 that modulates OSC2.
