### ISSUE TITLE
Map the presets kits to C1 or C3

### ISSUE THREAD

**Issue by iurienistor** [quamplex/geonkick#30]
Map the presets kits to C1 or C3. Request: https://github.com/Geonkick-Synthesizer/geonkick/issues/26

**Comment by o-bardiuk** [comment]
I mean this. Why kick drum is A4?
![image](https://github.com/Geonkick-Synthesizer/geonkick/assets/139021881/311f7a96-b2c7-439b-8800-9bb03dfca41e)

According to General Midi PERCUSSION Key Map, kick drum should be C1, and in most drum VST plugins a user expects C1 to be a kick drum.

![image](https://github.com/Geonkick-Synthesizer/geonkick/assets/139021881/50e24147-9740-4e9b-a4a4-7dc36676d401)

**Comment by iurienistor** [comment]
@o-bardiuk Yes, actually all the Geonkick presets need to be updated and revisited (remapping etc.).  This will create incompatibilities for older projects, but... anyway, I plant to updated them. This is just loading them, modifying and save. Also, if you think you can create even a new preset and want to be included in the Geonkick factory presets... create a merge request. All the presets are under CC0 (public domain).

**Comment by o-bardiuk** [comment]
> Also, if you think you can create even a new preset and want to be included in the Geonkick factory presets... create a merge request. 

Yes, I would like to do it and I know how to do it. But do Geonkick's presets include the sample part (audio) into the preset file when I save them? Or should I commit audio files too? I was going to use kick clicks for presets.

I know Serum saves single cycled waveforms into presets (fxp files) so they can take up to a few MB. 

It would be cool if geonkick presets were self-contained.

**UPD:** It looks like you do include the sample, that's awesome!

**Comment by iurienistor** [comment]
@o-bardiuk Yes, the audio is encoded as base64 and included into the preset file.
