### ISSUE TITLE
Geonkick in LibraZiK-2

### ISSUE THREAD

**Issue by trebmuh** [quamplex/geonkick#31]
Hi @iurienistor 
I've tried to send you an email, but have been refused to do so because "_550 High probability of spam_"... :sunglasses: 

Just to let you know that I've been putting GeonKick 1.6 in the LibraZiK-2 users repository.
I made a presentation page on the LibraZiK-2 doc (in French) :
https://librazik.tuxfamily.org/doc2/logiciels/GeonKick

Thanks for this nice piece of software.
Cheers,
Olivier

**Comment by iurienistor** [comment]
Hi @trebmuh, I am sorry I haven't received your email. Probably the hosting company of my email is exaggerating with security. It seams that I receive emails from everyone, but I'll check. I am happy to see Geonkick useful and I hope users will like more Geonkick when I'll release the next version with new features.
Best,
Iurie
