### ISSUE TITLE
Export adds extension, even if given filename already has the right one

### ISSUE THREAD

**Issue by SpotlightKid** [quamplex/geonkick#33]
E.g. when I enter `test1.wav` in the "File Name" field of the export dialog, a file with the name `test1.wav.wav` is created. It should be `test1.wav`

If I enter `test1.flac` but the format is set to e.g. "WAV 16", `test1.wav`, a file with the name `test1.flac.wav` is created. It should be also `test1.wav`.

If suggest that geonkick strips the extension, if it is one of `.flac`, `.ogg`, `.oga`, `.wave` or `.wav` and then appends the correct one.

**Comment by SpotlightKid** [comment]
This could be also done when another format option is selected and a filename has been already entered.

**Comment by iurienistor** [comment]
Fixed. Anyway if the file has the name in the input box X.Y.z and the format is wav the result will be X.Y.wav. I am thinking to allow the case when users want to use the dot instead, for example, space or undescore in the file name. The fix is in the master branch, but for now I'll not update the URL to binary (you'll have t build). It will come on 1.8 release. Thank you :)

**Comment by SpotlightKid** [comment]
> I am thinking to allow the case when users want to use the dot instead,

Thatswhy I suggested above to strip only known extensions of the supported formats. Note that `std::filesystem::path` also has a `replace_extension` method. Maybe would be worth investigating how it behaves when the filename ends only with a dot (e.g. `test.foo.`).

**Comment by iurienistor** [comment]
Yes, you are right, I've added now this. But the problem is that there is need for a more sophisticated   validation. For example, for  ".", "foo...", "foo.hidden"... ".foo", "...foo" and other use cases. For "foo....", it will be "foo.....wav" now. I think I'll open this issue as improvement.

**Comment by SpotlightKid** [comment]
> The fix is in the master branch, but for now I'll not update the URL to binary 

BTW, the geonkick Arch Linux package has been updated to version 1.6 yesterday, so you might want to update the README.

**Comment by iurienistor** [comment]
Ah, thank you :) ... I'll update :)
