### ISSUE TITLE
File / Directory selection dialog lists entries in reverse alphabetical order

### ISSUE THREAD

**Issue by SpotlightKid** [quamplex/geonkick#34]
![geonkick-file-selection](https://user-images.githubusercontent.com/5719151/62425715-94fa4200-b6dc-11e9-9be0-6d138f06ef35.png)

Affects directories as well as files.

**Comment by iurienistor** [comment]
Yes, that's true, I need to add sorting in a way to be efficient.

**Comment by iurienistor** [comment]
Fixed. Now foiders and files are sorted in alphabetical order, folders are showed first.
