### ISSUE TITLE
When Distortion is enabled on init preset, Volume and/or Drive is at max

### ISSUE THREAD

**Issue by SpotlightKid** [quamplex/geonkick#35]
... but the UI shows the Drive at min and Volume at ca. 70%. Changing the Drive via the slider has no effect. Only when the Volume is changed via the UI slider for the first time, does the Drive setting take effect.

![geonkick-distortion](https://user-images.githubusercontent.com/5719151/62425998-e526d380-b6df-11e9-8e97-1f1301e98450.png)

**Comment by iurienistor** [comment]
Yes, I confirm the issue. Thank you :)

**Comment by iurienistor** [comment]
Fixed. It is in the master. Also I have updated the binary. Thank you :)
