### ISSUE TITLE
Add bandpass filter mode

### ISSUE THREAD

**Issue by SpotlightKid** [quamplex/geonkick#36]
This would be especially useful for the noise filter.

Also, I would find a resonance setting instead of Q a lot more intuitive, i.e. with the highest cutoff emphasis at maximum value and with a much broader usable range than the current Q dial.

**Comment by iurienistor** [comment]
Yes, the current code for the filter has three modes LP, HP and BP... but haven't added the option in the UI for BP. There is a need to add it UI but to avoid popup and not to make the user to click 3 times in order to go back to first option for the filter.

**Comment by SpotlightKid** [comment]
If the number of filter models doesn't grow too much, a simple radio button selection would be even quicker.

**Comment by iurienistor** [comment]
Yes, I think it may work this, but only with short text, LP, HP, BP.

**Comment by SpotlightKid** [comment]
Just wanted to write something to the same effect ;)

**Comment by iurienistor** [comment]
It depends of what algorithm you are using. I have implemented "digital state variable filter", the result of which will give you all three types in one go.

**Comment by iurienistor** [comment]
Hey! I have just tested with BP, it adds really what I was missing... I am thinking why I have omitted BP  before?.... Thank you for this good suggestion! Now I am moving the code around and I'll add radiobuttons for UI for filter type. I'll commit it in master so you can use this, but officially release it in v1.8.

**Comment by SpotlightKid** [comment]
Cool, I'll be happy to test the new filter when you commit it.

**Comment by iurienistor** [comment]
Hi! Implemented. I made a commit on master branch. Later I'll add also the binary if everything is ok. Also I have added a new preset in examples/Snare-1_6.gkick directory that is based on Snare-1_5.gkick, but now it works better with BP filter from my point of view.
