### ISSUE TITLE
Using Geonkick on a headless RPi

### ISSUE THREAD

**Issue by Grahack** [quamplex/geonkick#37]
Hi all,

Is there a mean to use Geonkick only from the CLI?

Note: it would be ok to configure it with a GUI, then import the settings on the headless machine.

Thanks!

**Comment by iurienistor** [comment]
Hi, Geonkick doesn't support that.. to run as a daemon.  But I think you can run a minimalist lv2 host(as daemon) with Geonkick as a plugin... this will load only the DSP part with the preset. Anyway, Geonkick doesn't expose any control parameters, only a midi input for playing a key. I hope I understood your question.

**Comment by Grahack** [comment]
Thanks for your answer, happy coding and happy 2024!
