### ISSUE TITLE
Windows version NOT work in some DAWs

### ISSUE THREAD

**Issue by lehsa4017** [quamplex/geonkick#4]
Win 10 - 64 bit 
Ardour can find VST3 and LV2 but ableton and cakewalk Can't

**Comment by iurienistor** [comment]
@lehsa4017 If REAPER also not finding the plugin, than could you check if the system variable Path contains an entry related to Geonkick?... If not, than the installer needs a fix. Otherwise I'll check specifically these DAWs to see.

**Comment by lehsa4017** [comment]
Hi 
I don't use reaper but Geon found in my path 
![image](https://github.com/Geonkick-Synthesizer/geonkick/assets/119779161/c140987c-628c-4861-bd9d-eb6196f7b5c8)

**Comment by iurienistor** [comment]
@lehsa4017 Hi, thanks! I'll check with those daws to see hat is happening.

**Comment by iurienistor** [comment]
@lehsa4017 In Albeton Live 11 I see the plugin is found. The problem is that the GUI is shown small and cannot be resized because of the problem related to window dimension that I need to clarify.
![AlbetonGeonkick](https://github.com/Geonkick-Synthesizer/geonkick/assets/56111777/08cc585c-a95f-4bbd-b1ac-23788e8862bb)

**Comment by iurienistor** [comment]
@lehsa4017  Under  cakewalk I see everything is ok.
![image](https://github.com/Geonkick-Synthesizer/geonkick/assets/56111777/b3e3cd3f-e87a-438a-9bc9-016fe8a13cdd)

**Comment by lehsa4017** [comment]
in cakewalk pay attention to [VstScan.log](https://github.com/Geonkick-Synthesizer/geonkick/files/13483440/VstScan.log) it can find geon but return this error "NOT a VST plugin"

![image](https://github.com/Geonkick-Synthesizer/geonkick/assets/119779161/7b731ab8-41ce-4937-91f0-996ec5acfb4b)

**Comment by iurienistor** [comment]
@lehsa4017 Fixed the problem related to windows size in Ableton. Also fixed a problem that was causing failing to load the plugin in some hosts. Tested in hosts: Ableton, Bitwig, FL Studio, Ardour, Reaper... all find, play, and opens the GUI ok now. The fix will be available in the 3.0.1 release, that I plan to release tomorrow.
