### ISSUE TITLE
When saving a preset, letter S clears input, letter A selects all

### ISSUE THREAD

**Issue by o-bardiuk** [quamplex/geonkick#44]
Here is a video demonstration. Can't use `a` or `s` in the preset name.

https://drive.google.com/file/d/1I1A_jVdTJcEMkNk9__prCnfk1LZxLTY8/view?usp=sharing

**Comment by iurienistor** [comment]
@o-bardiuk What DAW is this? Could you try if this is reproducible in other DAW? I have tried to reproduce in Ardour, FL Studio and Bitwig, and I cannot reproduce.

**Comment by o-bardiuk** [comment]
It is Cubase, Win10, ok, I'll check.

**Comment by o-bardiuk** [comment]
Okay, sorry, you can close this. I tested in FL, Ableton and Reaper - it's all fine. Also I tested in Cubase again - it is also working. Maybe my keyboard lagged or something 🤔 sorry.
