### ISSUE TITLE
When I save a preset and then load it - there is still Default name in the title bar

### ISSUE THREAD

**Issue by o-bardiuk** [quamplex/geonkick#46]
![image](https://github.com/Geonkick-Synthesizer/geonkick/assets/139021881/2754c03a-ff98-40ee-b22f-2e9f121ac658)

**Comment by iurienistor** [comment]
This is because the name of the preset is not the same as the filename of the preset. Then the preset is loaded its name is taken from the contents of the file, not from the file name.

**Comment by o-bardiuk** [comment]
Yeah, I got that, I have checked the preset file. Wouldn't it help if the `Default` word is replaced with the file name on save for better convenience? In other way users would need to edit the files manually.

**Comment by iurienistor** [comment]
@o-bardiuk Yes, I think this can be done. I am planning to add the user to input the metadata when a preset is saved. and to show these metadata in the presets window when a preset is selected, or in other places of the UI. I want to show the author, url, license and other  info maybe. Thus, probably if the user will not provide a name for the preset... than the name will be replaced with the file name or something.
