### ISSUE TITLE
Preset navigator 

### ISSUE THREAD

**Issue by o-bardiuk** [quamplex/geonkick#50]
Hello, let's say I have created a bunch of presets (snares) and now I would like to test them in a beat. For example in Sonic Academy Kick 2 there is a way to navigate through presets with arrows pretty easily and quickly:
![image](https://github.com/Geonkick-Synthesizer/geonkick/assets/139021881/8e023597-21da-428e-8585-6d59786b5a88)

In Geonkick I need to open saved presets one by one or move them into the plugins factory folder. Yet there still no way to go through presets but at least there is a way to switch them quickly.

I think picking up a sound is very crucial for a plugin. That's why XLN XO VST is very popular.
Would be great to have something like this in Geonkick too. The way to walk through presets. Especially when the user base will grow. I think the plugin is very promising! I literally like every drum sound I have created and the process is very intuitive.

The same I would like to say about the sample browser. Would be easier to navigate through samples with up/down keys than mouse:
![image](https://github.com/Geonkick-Synthesizer/geonkick/assets/139021881/564e6a0e-7d6d-421d-bc2d-95e9298f3982)

**Comment by iurienistor** [comment]
Yes, the sample browser I plan improve, and switch between presets more easily. Also, in the kit tab probably I'll emmbed the presets browser because there is a need to navigate also between kits too.

Ok, navigate with keys, and load the preset on pressing enter? Because what you see in the preset browser are presets in the files, but not loaded.

**Comment by iurienistor** [comment]
Yes, I plan to improve the sample browser and the preset browser too. And the switch between the presets.

**Comment by iurienistor** [comment]
Actually the fie browser should support key up/ down, but I'll check, maybe is not working.

**Comment by iurienistor** [comment]
@o-bardiuk What I want to understand what does it mean to navigate... in geonkick presets are split by folders... like group... thus, the current preset should be shown in the box as 

MyKicks/kick1

When pressing next it goes

MyKicks/kick2

If I press again next and there is are presets in the group MyKicks... the it will go to 

OntherGroup/preset1 ... etc.

Than probably this box along the next/prev for presets, should have controls to change also groups... for navigation?

**Comment by iurienistor** [comment]
Also there are presets that have groups of presets.

**Comment by iurienistor** [comment]
Linked:

https://github.com/Geonkick-Synthesizer/geonkick/issues/52
https://github.com/Geonkick-Synthesizer/geonkick/issues/18
https://github.com/Geonkick-Synthesizer/geonkick/issues/46
