### ISSUE TITLE
Installer issue on Windows

### ISSUE THREAD

**Issue by hlzr** [quamplex/geonkick#74]
Hi, when I try to install on Windows, I cannot accept the licensing agreement.  Scrolling to the bottom of the GPL does not allow me to select the 'accept' radio button and continue.

**Comment by hlzr** [comment]
Upon further investigation, the binary in the "Relases" section of github work, but the ones on the website do not.

**Comment by iurienistor** [comment]
@hlzr The download link for the website binary points to the GitHub release binary, meaning the same binary is provided. I couldn't reproduce the issue, but let's see if anyone else encounters it. For now I'll keep this issue open.
