### ISSUE TITLE
Tracking geonkick downstream package repo integration 

### ISSUE THREAD

**Issue by luzpaz** [quamplex/geonkick#8]
<a href="https://repology.org/project/geonkick/versions">
    <img src="https://repology.org/badge/vertical-allrepos/geonkick.svg?columns=3&header=Geonkick" alt="Packaging status">
</a>

#### Linux
- [ ] Alpine
- [ ] Gentoo
- [ ] OpenSUSE

#### BSD
- [ ] FreeBSD

#### Windows 
- [ ] Chocolatey
- [ ] Winget

**Comment by iurienistor** [comment]
@luzpaz Hi, thanks for the link, very useful. What what are the check boxes for?

**Comment by luzpaz** [comment]
Downstream repos to get geonkick into.
