### ISSUE TITLE
old version - exe

### ISSUE THREAD

**Issue by DerozerDSP** [quamplex/geonkick#86]
Hi,

where can I download a old version of Geonkick?
I need the GeonkickWindowsInstaller-v3.3.0-x86_64.exe version, due to some problem on an old project I've made with it.

Can you link it here? On official website https://geonkick.org/2024/01/13/geonkick-version-3-3-0-has-been-released.html it seems borken.

Thanks

**Comment by iurienistor** [comment]
Hi, Geonkick project is no more providing the old ready-to run binaries. You can checkout the tag from the repository and build the binary by following the commands from the github/workflows/windows.yml.
