### ISSUE TITLE
CMake Error: Redkite is not implemented yet for MSYS

### ISSUE THREAD

**Issue by denalena** [quamplex/geonkick#88]
Hi! I'm trying to build this on Windows 10 according to the README. I installed MSYS2 UCRT64 and within it I installed the packages that are needed for compiling (or at least I thought so). But I get this error: `Redkite is not implemented yet for MSYS`

```
UCRT64 ~/geonkick-v3.5.0/build
$ cmake ..
-- Geonkick version: 3.5.0 (197888)
-- GKICK_ARCHITECTURE variable was not set use default x86_64
-- set optimisation compiler flags for x86_64
-- RapidJSON found. Headers: /ucrt64/lib/cmake/RapidJSON/../../../include
-- Checking for module 'jack'
--   Found jack, version 1.9.22
-- checking for LV2 library...
CMake Error at src/redkite/CMakeLists.txt:22 (message):
  Redkite is not implemented yet for MSYS


-- Configuring incomplete, errors occurred!
```

**Comment by iurienistor** [comment]
Hi! Your CMake/MSYS setup detects incorrect operating system. CMAKE_SYSTEM_NAME variable should be "Windows" and not "MSYS" operating system. -  https://cmake.org/cmake/help/latest/variable/CMAKE_SYSTEM_NAME.html
