### ISSUE TITLE
feature request: include the vst3 sdk

### ISSUE THREAD

**Issue by magnetophon** [quamplex/geonkick#9]
I'm updating the package for NixOS, and I noticed there is a VST3 version now, great!
Could you include the VST3 SDK in the source somehow, for example as a git submodule.
This would make it much easier to build.

Thanks!

**Comment by iurienistor** [comment]
Hi, vst sdk will not be included in the source code of Geonkick, nor as a module. The sdk is build by the Geonkick build system as an external target if you pass cmake -DVST3_SDK_PATH=full system path to VST3 SDK source code folder

**Comment by magnetophon** [comment]
Thanks for clearing that up, seems pretty final. :)
Would you mind telling me why you've made that decision?

**Comment by iurienistor** [comment]
@magnetophon   You can find here. https://gitlab.com/Geonkick-Synthesizer/geonkick/-/issues/2#note_1577457597
Also, Geonkick follows the Debian Upstream Guide  https://wiki.debian.org/UpstreamGuide not to include and distribute 3rd party libraries.

**Comment by magnetophon** [comment]
OK, thanks for clearing that up.
