### ISSUE TITLE
Samples only load in Oscillator 1 (?)

### ISSUE THREAD

**Issue by MaZe6K** [quamplex/geonkick#90]
It seems to me that I am unable to load more than one sample per layer, and that it's always loaded into Oscillator 1.
When I try to load a sample into Oscillator 2 or 3, it only changes the sample of Oscillator 1.

Win 10, FL Studio

**Comment by iurienistor** [comment]
@MaZe6K  When you load a sample from the samples tab (for example, for Osc2), the waveform of OSc2 does not automatically switch to "sample," and the oscillator is not turned on. Make sure Osc2 is set to "sample" and that it is turned on. This process should probably happen automatically, but I'll review it again once changes are made to improve the workflow for loading samples.

**Comment by MaZe6K** [comment]
I didn't realize I need to select the oscillator in the sample browser, below the sample display... when I click on load sample on Osc 2 or 3, the sample browser opens, but Osc 1 is still selected by default.

No problem, though, just overlooked it.

**Comment by iurienistor** [comment]
"Osc 2 or 3, the sample browser opens, but Osc 1 is still selected by default."... yes, this a little inconvenient, but I plant to improve this workflow in the next releases.
